# Generated by Django 2.2.5 on 2020-02-07 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('ucountry', django_countries.fields.CountryField(max_length=2)),
                ('ucity', models.CharField(max_length=256)),
                ('ustreetAddress', models.CharField(max_length=256)),
                ('umembership', models.CharField(choices=[('free', 'Free'), ('minimal', 'Minimal'), ('premium', 'Premium')], max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='WebSites',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('wname', models.CharField(max_length=255)),
                ('wpath', models.CharField(max_length=255)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('SITEOPT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.WebSites')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('pmthid', models.AutoField(primary_key=True, serialize=False)),
                ('paymethod', models.CharField(choices=[('FAW', 'fawry'), ('VFC', 'vodafone cash'), ('CC', 'Credit card'), ('C', 'Cash')], max_length=200)),
                ('userp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False, verbose_name=django.db.models.constraints.UniqueConstraint)),
                ('pname', models.CharField(max_length=255)),
                ('ppath', models.CharField(max_length=500)),
                ('SITEPAGE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.WebSites')),
            ],
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('eid', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name=django.db.models.constraints.UniqueConstraint)),
                ('index', models.IntegerField()),
                ('PPATH', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Pages')),
            ],
        ),
        migrations.CreateModel(
            name='ElementClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=500)),
                ('CLASSELEMENT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Elements')),
            ],
        ),
        migrations.CreateModel(
            name='ElementAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.CharField(max_length=500)),
                ('ATTRIELEMENT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Elements')),
            ],
        ),
    ]
