# Generated by Django 2.2.5 on 2020-01-24 17:22

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=264)),
                ('upassword', models.CharField(max_length=500)),
                ('ucountry', models.CharField(max_length=256)),
                ('ucity', models.CharField(max_length=256)),
                ('ustreetAddress', models.CharField(max_length=256)),
                ('ufname', models.CharField(max_length=256)),
                ('ulname', models.CharField(max_length=256)),
                ('umembership', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='WebSites',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('wname', models.CharField(max_length=255)),
                ('wpath', models.CharField(max_length=255)),
                ('USERSITE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('SITEOPT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.WebSites')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymethod', models.CharField(blank=True, max_length=200)),
                ('userpayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False, verbose_name=django.db.models.constraints.UniqueConstraint)),
                ('pname', models.CharField(max_length=255)),
                ('ppath', models.CharField(max_length=500)),
                ('SITEPAGE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.WebSites')),
            ],
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('eid', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name=django.db.models.constraints.UniqueConstraint)),
                ('index', models.IntegerField()),
                ('PPATH', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Pages')),
            ],
        ),
    ]
