# Generated by Django 2.2.5 on 2020-01-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=500)),
                ('CLASSELEMENT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Elements')),
            ],
        ),
        migrations.CreateModel(
            name='ElementAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.CharField(max_length=500)),
                ('ATTRIELEMENT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Elements')),
            ],
        ),
    ]
