# Generated by Django 2.2.5 on 2020-02-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_elementattributes_elementclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='umail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='umembership',
            field=models.CharField(max_length=225),
        ),
    ]
